package fr.emcastro.jdbcretyper.jdbc;

import static org.junit.jupiter.api.Assertions.*;
import static org.mockito.Mockito.*;

import java.sql.CallableStatement;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;
import org.mockito.Mock;
import org.mockito.junit.jupiter.MockitoExtension;

import fr.emcastro.jdbcretyper.transform.TypeTransformerRegistry;

@ExtendWith(MockitoExtension.class)
class RetyperConnectionTest {

    @Mock
    private Connection mockConnection;

    @Mock
    private TypeTransformerRegistry registry;

    @Mock
    private Statement mockStatement;

    @Mock
    private PreparedStatement mockPreparedStatement;

    @Mock
    private CallableStatement mockCallableStatement;

    private RetyperConnection connection;

    @BeforeEach
    void setUp() {
        connection = new RetyperConnection(mockConnection, registry);
    }

    @Test
    // Check that createStatement() wraps the driver's Statement in a
    // RetyperStatement carrying the registry and connection reference.
    void createStatement_returnsRetyperStatement() throws SQLException {
        when(mockConnection.createStatement()).thenReturn(mockStatement);

        assertInstanceOf(RetyperStatement.class, connection.createStatement());
    }

    @Test
    // Check that prepareStatement() wraps the driver's PreparedStatement
    // in a RetyperPreparedStatement for parameter transformation.
    void prepareStatement_returnsRetyperPreparedStatement() throws SQLException {
        when(mockConnection.prepareStatement(anyString())).thenReturn(mockPreparedStatement);

        assertInstanceOf(RetyperPreparedStatement.class, connection.prepareStatement("SELECT 1"));
    }

    @Test
    // Check that prepareCall() wraps the driver's CallableStatement in
    // a RetyperCallableStatement for OUT parameter transformation.
    void prepareCall_returnsRetyperCallableStatement() throws SQLException {
        when(mockConnection.prepareCall(anyString())).thenReturn(mockCallableStatement);

        assertInstanceOf(RetyperCallableStatement.class, connection.prepareCall("{call proc()}"));
    }

    @Test
    // Check that unwrap(Connection.class) returns the underlying driver
    // Connection when the requested type matches the delegate.
    void unwrap_returnsWrappedIfInstance() throws SQLException {
        assertSame(mockConnection, connection.unwrap(Connection.class));
    }

    @Test
    // Check that isWrapperFor(Connection.class) is true because the
    // wrapped Connection implements that interface.
    void isWrapperFor_trueForWrappedInstance() throws SQLException {
        assertTrue(connection.isWrapperFor(Connection.class));
    }

    @Test
    // Check that close() delegates to the wrapped Connection without
    // additional cleanup or transformation.
    void close_delegatesToWrapped() throws SQLException {
        connection.close();

        verify(mockConnection).close();
    }

    @Test
    // Check that createStatement(int, int) wraps the driver's Statement
    // in a RetyperStatement carrying the registry and connection.
    void createStatement_withParams_returnsRetyperStatement() throws SQLException {
        when(mockConnection.createStatement(anyInt(), anyInt())).thenReturn(mockStatement);

        assertInstanceOf(RetyperStatement.class, connection.createStatement(ResultSet.TYPE_FORWARD_ONLY, ResultSet.CONCUR_READ_ONLY));
    }

    @Test
    // Check that createStatement(int, int, int) wraps the driver's
    // Statement in a RetyperStatement with all parameters preserved.
    void createStatement_withAllParams_returnsRetyperStatement() throws SQLException {
        when(mockConnection.createStatement(anyInt(), anyInt(), anyInt())).thenReturn(mockStatement);

        assertInstanceOf(RetyperStatement.class,
                connection.createStatement(ResultSet.TYPE_FORWARD_ONLY, ResultSet.CONCUR_READ_ONLY, ResultSet.CLOSE_CURSORS_AT_COMMIT));
    }

    @Test
    // Check that prepareStatement(String, autoGeneratedKeys) wraps the
    // driver's PreparedStatement in a RetyperPreparedStatement.
    void prepareStatement_withAutoGeneratedKeys_returnsRetyperPreparedStatement() throws SQLException {
        when(mockConnection.prepareStatement(anyString(), anyInt())).thenReturn(mockPreparedStatement);

        assertInstanceOf(RetyperPreparedStatement.class, connection.prepareStatement("INSERT INTO t VALUES (?)", Statement.RETURN_GENERATED_KEYS));
    }

    @Test
    // Check that prepareStatement(String, int[]) wraps the driver's
    // PreparedStatement in a RetyperPreparedStatement for column indexes.
    void prepareStatement_withColumnIndexes_returnsRetyperPreparedStatement() throws SQLException {
        when(mockConnection.prepareStatement(anyString(), any(int[].class))).thenReturn(mockPreparedStatement);

        assertInstanceOf(RetyperPreparedStatement.class, connection.prepareStatement("INSERT INTO t VALUES (?)", new int[] {1}));
    }

    @Test
    // Check that prepareStatement(String, String[]) wraps the driver's
    // PreparedStatement in a RetyperPreparedStatement for column names.
    void prepareStatement_withColumnNames_returnsRetyperPreparedStatement() throws SQLException {
        when(mockConnection.prepareStatement(anyString(), any(String[].class))).thenReturn(mockPreparedStatement);

        assertInstanceOf(RetyperPreparedStatement.class, connection.prepareStatement("INSERT INTO t VALUES (?)", new String[] {"col"}));
    }

    @Test
    // Check that prepareStatement(String, int, int) wraps the driver's
    // PreparedStatement in a RetyperPreparedStatement with result set params.
    void prepareStatement_withResultSetParams_returnsRetyperPreparedStatement() throws SQLException {
        when(mockConnection.prepareStatement(anyString(), anyInt(), anyInt())).thenReturn(mockPreparedStatement);

        assertInstanceOf(RetyperPreparedStatement.class,
                connection.prepareStatement("SELECT 1", ResultSet.TYPE_FORWARD_ONLY, ResultSet.CONCUR_READ_ONLY));
    }

    @Test
    // Check that prepareStatement(String, int, int, int) wraps the
    // driver's PreparedStatement in a RetyperPreparedStatement.
    void prepareStatement_withAllParams_returnsRetyperPreparedStatement() throws SQLException {
        when(mockConnection.prepareStatement(anyString(), anyInt(), anyInt(), anyInt())).thenReturn(mockPreparedStatement);

        assertInstanceOf(RetyperPreparedStatement.class,
                connection.prepareStatement("SELECT 1", ResultSet.TYPE_FORWARD_ONLY, ResultSet.CONCUR_READ_ONLY, ResultSet.CLOSE_CURSORS_AT_COMMIT));
    }

    @Test
    // Check that prepareCall(String, int, int) wraps the driver's
    // CallableStatement in a RetyperCallableStatement with result set params.
    void prepareCall_withResultSetParams_returnsRetyperCallableStatement() throws SQLException {
        when(mockConnection.prepareCall(anyString(), anyInt(), anyInt())).thenReturn(mockCallableStatement);

        assertInstanceOf(RetyperCallableStatement.class,
                connection.prepareCall("{call proc()}", ResultSet.TYPE_FORWARD_ONLY, ResultSet.CONCUR_READ_ONLY));
    }

    @Test
    // Check that prepareCall(String, int, int, int) wraps the driver's
    // CallableStatement in a RetyperCallableStatement with all parameters.
    void prepareCall_withAllParams_returnsRetyperCallableStatement() throws SQLException {
        when(mockConnection.prepareCall(anyString(), anyInt(), anyInt(), anyInt())).thenReturn(mockCallableStatement);

        assertInstanceOf(RetyperCallableStatement.class,
                connection.prepareCall("{call proc()}", ResultSet.TYPE_FORWARD_ONLY, ResultSet.CONCUR_READ_ONLY, ResultSet.CLOSE_CURSORS_AT_COMMIT));
    }
}
