# Configuration de la base de données PostgreSQL
spring.datasource.driver-class-name=org.postgresql.Driver

spring.datasource.url=jdbc:postgresql://localhost:5432/cadastre_osm?currentSchema=osm_entreprise
spring.datasource.username=cad_ad_dg
spring.datasource.password=cad_ad_dg_pass

# Configuration de Hibernate (optionnel si utilisé)
spring.jpa.hibernate.ddl-auto=update

# Niveau de journalisation pour les requêtes SQL
logging.level.org.springframework.jdbc.core=DEBUG
