package fr.emcastro.jdbcretyper.jdbc.delegation;

import static org.junit.jupiter.api.Assertions.*;
import static org.mockito.Mockito.*;

import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.SQLWarning;
import java.sql.Statement;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;
import org.mockito.Mock;
import org.mockito.junit.jupiter.MockitoExtension;

import fr.emcastro.jdbcretyper.jdbc.RetyperConnection;
import fr.emcastro.jdbcretyper.jdbc.RetyperStatement;
import fr.emcastro.jdbcretyper.transform.TypeTransformerRegistry;

@ExtendWith(MockitoExtension.class)
class RetyperStatementDelegationTest {

    @Mock
    private Statement mockStatement;

    @Mock
    private TypeTransformerRegistry registry;

    @Mock
    private RetyperConnection mockConnection;

    private RetyperStatement statement;

    @BeforeEach
    void setUp() {
        statement = new RetyperStatement(mockStatement, registry, mockConnection);
    }

    @Test
    // Check that addBatch(String) delegates to the underlying Statement
    // without additional transformation.
    void addBatch_delegates() throws SQLException {
        statement.addBatch("SELECT 1");
        verify(mockStatement).addBatch("SELECT 1");
    }

    @Test
    // Check that cancel() delegates to the underlying Statement without
    // additional transformation.
    void cancel_delegates() throws SQLException {
        statement.cancel();
        verify(mockStatement).cancel();
    }

    @Test
    // Check that clearBatch() delegates to the underlying Statement
    // without additional transformation.
    void clearBatch_delegates() throws SQLException {
        statement.clearBatch();
        verify(mockStatement).clearBatch();
    }

    @Test
    // Check that clearWarnings() delegates to the underlying Statement
    // without additional transformation.
    void clearWarnings_delegates() throws SQLException {
        statement.clearWarnings();
        verify(mockStatement).clearWarnings();
    }

    @Test
    // Check that close() delegates to the underlying Statement without
    // additional transformation.
    void close_delegates() throws SQLException {
        statement.close();
        verify(mockStatement).close();
    }

    @Test
    // Check that closeOnCompletion() delegates to the underlying Statement
    // without additional transformation.
    void closeOnCompletion_delegates() throws SQLException {
        statement.closeOnCompletion();
        verify(mockStatement).closeOnCompletion();
    }

    @Test
    // Check that execute(String) delegates to the underlying Statement
    // without additional transformation.
    void execute_delegates() throws SQLException {
        when(mockStatement.execute("SELECT 1")).thenReturn(true);
        assertTrue(statement.execute("SELECT 1"));
        verify(mockStatement).execute("SELECT 1");
    }

    @Test
    // Check that execute(String, autoGeneratedKeys) delegates to the
    // underlying Statement without additional transformation.
    void execute_withAutoGeneratedKeys_delegates() throws SQLException {
        when(mockStatement.execute("INSERT INTO t VALUES (1)", Statement.RETURN_GENERATED_KEYS)).thenReturn(true);
        assertTrue(statement.execute("INSERT INTO t VALUES (1)", Statement.RETURN_GENERATED_KEYS));
        verify(mockStatement).execute("INSERT INTO t VALUES (1)", Statement.RETURN_GENERATED_KEYS);
    }

    @Test
    // Check that execute(String, columnIndexes) delegates to the
    // underlying Statement without additional transformation.
    void execute_withColumnIndexes_delegates() throws SQLException {
        when(mockStatement.execute("INSERT INTO t VALUES (1)", new int[] {1})).thenReturn(true);
        assertTrue(statement.execute("INSERT INTO t VALUES (1)", new int[] {1}));
        verify(mockStatement).execute("INSERT INTO t VALUES (1)", new int[] {1});
    }

    @Test
    // Check that execute(String, columnNames) delegates to the
    // underlying Statement without additional transformation.
    void execute_withColumnNames_delegates() throws SQLException {
        when(mockStatement.execute("INSERT INTO t VALUES (1)", new String[] {"col"})).thenReturn(true);
        assertTrue(statement.execute("INSERT INTO t VALUES (1)", new String[] {"col"}));
        verify(mockStatement).execute("INSERT INTO t VALUES (1)", new String[] {"col"});
    }

    @Test
    // Check that executeUpdate(String) delegates to the underlying
    // Statement without additional transformation.
    void executeUpdate_delegates() throws SQLException {
        when(mockStatement.executeUpdate("DELETE FROM t")).thenReturn(1);
        assertEquals(1, statement.executeUpdate("DELETE FROM t"));
        verify(mockStatement).executeUpdate("DELETE FROM t");
    }

    @Test
    // Check that executeUpdate(String, autoGeneratedKeys) delegates to
    // the underlying Statement without additional transformation.
    void executeUpdate_withAutoGeneratedKeys_delegates() throws SQLException {
        when(mockStatement.executeUpdate("DELETE FROM t", Statement.RETURN_GENERATED_KEYS)).thenReturn(1);
        assertEquals(1, statement.executeUpdate("DELETE FROM t", Statement.RETURN_GENERATED_KEYS));
        verify(mockStatement).executeUpdate("DELETE FROM t", Statement.RETURN_GENERATED_KEYS);
    }

    @Test
    // Check that executeUpdate(String, columnIndexes) delegates to the
    // underlying Statement without additional transformation.
    void executeUpdate_withColumnIndexes_delegates() throws SQLException {
        when(mockStatement.executeUpdate("DELETE FROM t", new int[] {1})).thenReturn(1);
        assertEquals(1, statement.executeUpdate("DELETE FROM t", new int[] {1}));
        verify(mockStatement).executeUpdate("DELETE FROM t", new int[] {1});
    }

    @Test
    // Check that executeUpdate(String, columnNames) delegates to the
    // underlying Statement without additional transformation.
    void executeUpdate_withColumnNames_delegates() throws SQLException {
        when(mockStatement.executeUpdate("DELETE FROM t", new String[] {"col"})).thenReturn(1);
        assertEquals(1, statement.executeUpdate("DELETE FROM t", new String[] {"col"}));
        verify(mockStatement).executeUpdate("DELETE FROM t", new String[] {"col"});
    }

    @Test
    // Check that executeBatch() delegates to the underlying Statement
    // without additional transformation.
    void executeBatch_delegates() throws SQLException {
        when(mockStatement.executeBatch()).thenReturn(new int[] {1, 2});
        assertArrayEquals(new int[] {1, 2}, statement.executeBatch());
        verify(mockStatement).executeBatch();
    }

    @Test
    // Check that getFetchDirection() delegates to the underlying Statement
    // without additional transformation.
    void getFetchDirection_delegates() throws SQLException {
        when(mockStatement.getFetchDirection()).thenReturn(ResultSet.FETCH_FORWARD);
        assertEquals(ResultSet.FETCH_FORWARD, statement.getFetchDirection());
        verify(mockStatement).getFetchDirection();
    }

    @Test
    // Check that getFetchSize() delegates to the underlying Statement
    // without additional transformation.
    void getFetchSize_delegates() throws SQLException {
        when(mockStatement.getFetchSize()).thenReturn(100);
        assertEquals(100, statement.getFetchSize());
        verify(mockStatement).getFetchSize();
    }

    @Test
    // Check that getMaxFieldSize() delegates to the underlying Statement
    // without additional transformation.
    void getMaxFieldSize_delegates() throws SQLException {
        when(mockStatement.getMaxFieldSize()).thenReturn(4096);
        assertEquals(4096, statement.getMaxFieldSize());
        verify(mockStatement).getMaxFieldSize();
    }

    @Test
    // Check that getMaxRows() delegates to the underlying Statement
    // without additional transformation.
    void getMaxRows_delegates() throws SQLException {
        when(mockStatement.getMaxRows()).thenReturn(1000);
        assertEquals(1000, statement.getMaxRows());
        verify(mockStatement).getMaxRows();
    }

    @Test
    // Check that getMoreResults() delegates to the underlying Statement
    // without additional transformation.
    void getMoreResults_delegates() throws SQLException {
        when(mockStatement.getMoreResults()).thenReturn(false);
        assertFalse(statement.getMoreResults());
        verify(mockStatement).getMoreResults();
    }

    @Test
    // Check that getMoreResults(int) delegates to the underlying Statement
    // without additional transformation.
    void getMoreResults_withCurrent_delegates() throws SQLException {
        when(mockStatement.getMoreResults(Statement.KEEP_CURRENT_RESULT)).thenReturn(false);
        assertFalse(statement.getMoreResults(Statement.KEEP_CURRENT_RESULT));
        verify(mockStatement).getMoreResults(Statement.KEEP_CURRENT_RESULT);
    }

    @Test
    // Check that getQueryTimeout() delegates to the underlying Statement
    // without additional transformation.
    void getQueryTimeout_delegates() throws SQLException {
        when(mockStatement.getQueryTimeout()).thenReturn(30);
        assertEquals(30, statement.getQueryTimeout());
        verify(mockStatement).getQueryTimeout();
    }

    @Test
    // Check that getResultSetConcurrency() delegates to the underlying
    // Statement without additional transformation.
    void getResultSetConcurrency_delegates() throws SQLException {
        when(mockStatement.getResultSetConcurrency()).thenReturn(ResultSet.CONCUR_READ_ONLY);
        assertEquals(ResultSet.CONCUR_READ_ONLY, statement.getResultSetConcurrency());
        verify(mockStatement).getResultSetConcurrency();
    }

    @Test
    // Check that getResultSetHoldability() delegates to the underlying
    // Statement without additional transformation.
    void getResultSetHoldability_delegates() throws SQLException {
        when(mockStatement.getResultSetHoldability()).thenReturn(ResultSet.CLOSE_CURSORS_AT_COMMIT);
        assertEquals(ResultSet.CLOSE_CURSORS_AT_COMMIT, statement.getResultSetHoldability());
        verify(mockStatement).getResultSetHoldability();
    }

    @Test
    // Check that getResultSetType() delegates to the underlying Statement
    // without additional transformation.
    void getResultSetType_delegates() throws SQLException {
        when(mockStatement.getResultSetType()).thenReturn(ResultSet.TYPE_FORWARD_ONLY);
        assertEquals(ResultSet.TYPE_FORWARD_ONLY, statement.getResultSetType());
        verify(mockStatement).getResultSetType();
    }

    @Test
    // Check that getUpdateCount() delegates to the underlying Statement
    // without additional transformation.
    void getUpdateCount_delegates() throws SQLException {
        when(mockStatement.getUpdateCount()).thenReturn(5);
        assertEquals(5, statement.getUpdateCount());
        verify(mockStatement).getUpdateCount();
    }

    @Test
    // Check that getWarnings() delegates to the underlying Statement
    // without additional transformation.
    void getWarnings_delegates() throws SQLException {
        SQLWarning warning = new SQLWarning("test");
        when(mockStatement.getWarnings()).thenReturn(warning);
        assertSame(warning, statement.getWarnings());
        verify(mockStatement).getWarnings();
    }

    @Test
    // Check that isCloseOnCompletion() delegates to the underlying
    // Statement without additional transformation.
    void isCloseOnCompletion_delegates() throws SQLException {
        when(mockStatement.isCloseOnCompletion()).thenReturn(true);
        assertTrue(statement.isCloseOnCompletion());
        verify(mockStatement).isCloseOnCompletion();
    }

    @Test
    // Check that isClosed() delegates to the underlying Statement without
    // additional transformation.
    void isClosed_delegates() throws SQLException {
        when(mockStatement.isClosed()).thenReturn(true);
        assertTrue(statement.isClosed());
        verify(mockStatement).isClosed();
    }

    @Test
    // Check that isPoolable() delegates to the underlying Statement
    // without additional transformation.
    void isPoolable_delegates() throws SQLException {
        when(mockStatement.isPoolable()).thenReturn(true);
        assertTrue(statement.isPoolable());
        verify(mockStatement).isPoolable();
    }

    @Test
    // Check that setCursorName(String) delegates to the underlying
    // Statement without additional transformation.
    void setCursorName_delegates() throws SQLException {
        statement.setCursorName("myCursor");
        verify(mockStatement).setCursorName("myCursor");
    }

    @Test
    // Check that setEscapeProcessing(boolean) delegates to the underlying
    // Statement without additional transformation.
    void setEscapeProcessing_delegates() throws SQLException {
        statement.setEscapeProcessing(true);
        verify(mockStatement).setEscapeProcessing(true);
    }

    @Test
    // Check that setFetchDirection(int) delegates to the underlying
    // Statement without additional transformation.
    void setFetchDirection_delegates() throws SQLException {
        statement.setFetchDirection(ResultSet.FETCH_FORWARD);
        verify(mockStatement).setFetchDirection(ResultSet.FETCH_FORWARD);
    }

    @Test
    // Check that setFetchSize(int) delegates to the underlying Statement
    // without additional transformation.
    void setFetchSize_delegates() throws SQLException {
        statement.setFetchSize(50);
        verify(mockStatement).setFetchSize(50);
    }

    @Test
    // Check that setMaxFieldSize(int) delegates to the underlying
    // Statement without additional transformation.
    void setMaxFieldSize_delegates() throws SQLException {
        statement.setMaxFieldSize(2048);
        verify(mockStatement).setMaxFieldSize(2048);
    }

    @Test
    // Check that setMaxRows(int) delegates to the underlying Statement
    // without additional transformation.
    void setMaxRows_delegates() throws SQLException {
        statement.setMaxRows(500);
        verify(mockStatement).setMaxRows(500);
    }

    @Test
    // Check that setPoolable(boolean) delegates to the underlying
    // Statement without additional transformation.
    void setPoolable_delegates() throws SQLException {
        statement.setPoolable(true);
        verify(mockStatement).setPoolable(true);
    }

    @Test
    // Check that setQueryTimeout(int) delegates to the underlying
    // Statement without additional transformation.
    void setQueryTimeout_delegates() throws SQLException {
        statement.setQueryTimeout(60);
        verify(mockStatement).setQueryTimeout(60);
    }
}
